### ISSUE TITLE
Crash on iOS when call DocumentReader.showScanner()

### ISSUE THREAD

**Issue by ChenPingSheng** [regulaforensics/DocumentReader-Flutter#15]
flutter_document_reader_api: ^6.2.0
flutter_document_reader_core_fullrfid: ^6.2.0
macOS Monterey 12.2.1, Xcode 13.3, flutter 2.8.1
![image](https://user-images.githubusercontent.com/14194096/160606627-9c342803-824a-4125-89d1-d4b28072ea10.png)

**Comment by pkondrashkov** [comment]
Hi, @ChenPingSheng!

Thank you for reporting this issue, we are aware of this crash. We are currently working on fixing this problem.

For now, in order to avoid this issue, please make sure to call `initializeReader` method before calling any other functionality. 
This is the only intended way to use our SDK, however it happens to be that we have a crash if there was no initialization call at all.

https://docs.regulaforensics.com/develop/doc-reader-sdk/mobile/flutter/initialization/

Best regards,
Pavel

**Comment by ChenPingSheng** [comment]
@pkondrashkov Thanks for the quick reply, I will try it.

**Comment by bqubique** [comment]
For me, the issue was the device orientation. I enabled Portrait, Upside Down, Landscape Left/Right and it worked. I guess the activity started off in one of the orientations above that I had not enabled, and enabling it let me see the viewfinder of the camera. Another note, the above solution by [pkondrashkov](https://github.com/pkondrashkov) did not help me unfortunately, but it might be a good practice nonetheless.
